PermissionProvider added
CloudNetService/CloudNet-v2 pull request #12
Opened 2018-06-26 19:15 UTC by CloudNETWebNetwork

Added the PermissionProvieder Class to make it easier for all users to use the Cloud permission module.

2018-06-27 20:31 UTC, Tammo0987 requested changes
Generally a good idea, but you can do some things better. Here are my suggestions :)

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private long claculateDays(int value) { return (System.currentTimeMillis() + ((TimeUnit.DAYS.toMillis(value)))); }
Please rename "claculateDays" to "calculateDays" :)

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private long claculateDays(int value) { return (System.currentTimeMillis() + ((TimeUnit.DAYS.toMillis(value)))); }
And remove the brackets around the addition of System.currentTimeMillis() + TimeUnit.DAYS.toMillis(value)

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupPrefix(String group)
Please return null if the PermissionPool **not** contains the group and return as default the group. This is for better understanding, what the method should return.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupSuffix(String group)
Here also the same as above.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupDisplay(String group)
And here :)

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Collection<String> getImplementedGroup(String group)
And here :)

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Integer getJoinPower(String player)
Return an int instead of an Integer Object. Performance reasons.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Integer getGroupJoinPower(String group)
Return an int instead of an Integer Object. Performance reasons.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Integer getPlayerGroupTagID(String player)
Return an int instead of an Integer Object. Performance reasons.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public long getPlayerGroupRemainingTime(String player)
Please use the group as parameter or something else, but this is actually not so good.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPermissionGrouponServergroup(String permissiongroup, String permission, String servergroup)
The name of the method does not apply to the Java conventions and is maybe to long to understand.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPermissionGrouponServergroup(String permissiongroup, String permission, String servergroup)
The name of the method does not apply to the Java conventions and is maybe to long to understand.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPlayertoGroup(String player, String group, Integer timeindays)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPermissionGroup(String permissiongroup, String permission)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPermissionGroup(String permissiongroup, String permission)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPlayer(String player, String permission)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPlayer(String player, String permission)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePlayerfromGroup(String group, String player)
The name of the method does not apply to the Java conventions.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePlayerfromGroup(String group, String player)
Also you could change the statements, because you can make them easier in my opinion.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +                return stringBuilder.substring(0);
Please use instead of substring the toString method.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +                return stringBuilder.substring(0);
And return the stringBuilder as default value and change your statements for better understanding, what the method should return normally.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Collection<PermissionGroup> getGroups()
Here the same with the return value.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setJoinPower(String group, Integer joinpower)
Change the Integer parameter to an int.

2018-06-27 20:31 UTC, Tammo0987 commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setTagID(String group, Integer TagID)
And here also, change the Integer to an int.

2018-06-28 12:01 UTC, GiantTreeLP requested changes
Please fix your documentation and coding style

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> + */
Please add proper documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +     */
Why should nobody edit this?
Also clean up the comments

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    /*------------------------*/
This BS is not needed

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +     */
What does this method do?
Please fix up your documentation and refer to the relevant methods using `@see`

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private PermissionGroup getPlayerGroup(String player)
Why take a String? A player is either a `Player`, `CloudPlayer` or best `OfflinePlayer`.

You might also rename this method to `getPermissionGroup` then

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void sendDebug(String message)
Remove this method, it is not needed.

If necessary, create proper unit tests.

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private PermissionGroup getPlayerGroup(UUID uuid)
See my comments to the other `getPlayerGroup` method

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private void updatePlayer(OfflinePlayer offlinePlayer)
Please add missing documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setDebug(boolean debug) { this.debug = debug; }
Remove this together with the weird debug method

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public boolean isDebug() { return this.debug; }
Remove this together with the weird debug method

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private void updatePermissionGroup(PermissionGroup permissionGroup)
Please add missing documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private long claculateDays(int value) { return (System.currentTimeMillis() + ((TimeUnit.DAYS.toMillis(value)))); }
Please also add the missing documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    /*------------------------*/
Nobody needs these weird comments, remove them

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getDisplay(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getDisplay(UUID uuid)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getSuffix(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getSuffix(UUID uuid)
Fix the documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getPrefix(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getPrefix(UUID uuid)
Fix the documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupName(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupName(UUID uuid)
Fix the documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupPrefix(String group)
Also rename the parameter to something proper like `groupName`
And add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public boolean isInGroup(String group, String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getGroupDisplay(String group)
Also rename the parameter to something proper like `groupName`
And add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Collection<String> getImplementedGroups(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Collection<String> getImplementedGroup(String group)
Also rename the parameter to something proper like `groupName`
And add documentation.
Rename the method to reflect the return type `getImplementedGroups`

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Integer getJoinPower(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Integer getGroupJoinPower(String group)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Map<String, Boolean> getPlayerPermissions(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Map<String, Object> getPlayerServerPermissions(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public long getPlayerGroupRemainingTime(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPlayer(String player, String permission)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPlayer(String player, String permission)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void createPermissionGroup(String permissiongroup)
Add documentation and return the new group, if creation was successful

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPermissionGroup(String permissiongroup, String permission)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPermissionGroup(String permissiongroup, String permission)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPermissiontoPermissionGrouponServergroup(String permissiongroup, String permission, String servergroup)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePermissionfromPermissionGrouponServergroup(String permissiongroup, String permission, String servergroup)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setPlayerGroups(String player, String group, Integer timeindays)
Add documentation and take in a player, not a String
Also use primitive types when possible

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void addPlayertoGroup(String player, String group, Integer timeindays)
Add documentation and take in a player, not a String
Also use primitive types

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void removePlayerfromGroup(String group, String player)
Add documentation and take in a player, not a String

This should also be optimized

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getPlayerGroups(String player)
Add documentation and take in a player, not a String

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public Collection<PermissionGroup> getGroups()
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public PermissionGroup getPermissionGroup(String group)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setDisplay(String group, String display)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setPrefix(String group, String prefix)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setSuffix(String group, String suffix)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setDefaultGroup(String group)
Add documentation

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setJoinPower(String group, Integer joinpower)
Add documentation and use primitive types

2018-06-28 12:01 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public void setTagID(String group, Integer TagID)
Add documentation and use primitive types

2018-07-12 15:14 UTC, GiantTreeLP reviewed
Everything should be static as the state of the class is never used anywhere..
Also fix the documentation, the description comes first, followed by parameters, then return, then throws and lastly see other

2018-07-12 15:14 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private void updatePlayer(OfflinePlayer offlinePlayer)
Could be static

2018-07-12 15:14 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private void updatePermissionGroup(PermissionGroup permissionGroup)
Could be static

2018-07-12 15:14 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    private long calculateDays(int value) { return System.currentTimeMillis() + ((TimeUnit.DAYS.toMillis(value))); }
Could be static

2018-07-12 15:14 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getDisplay(OfflinePlayer offlinePlayer)
could be static

2018-07-12 15:14 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/player/PermissionProvider.java
> +    public String getDisplay(UUID uuid)
could be static

2018-07-19 00:36 UTC, GiantTreeLP approved these changes

2018-07-19 00:36 UTC, merged