Add haste support for log command - Update 2.1.16
CloudNetService/CloudNet-v2 pull request #131
Opened 2019-04-27 20:11 UTC by MeinerLP1

2019-04-27 20:47 UTC, MeinerLP1 commented
You can add as self in the Config a Haste Server

2019-04-27 21:09 UTC, realPanamo commented
I know, but I mean as a default

2019-04-27 21:27 UTC, MeinerLP1 commented
Maybe optional update or pr

2019-07-30 19:01 UTC, GiantTreeLP commented
This needs to be rebased and the unnecessary commits need to be removed.

2019-08-30 09:37 UTC, GiantTreeLP commented
As with the other pull requests: please remove unnecessary files and commits that are part of other pull requests.

2019-08-30 09:59 UTC, MeinerLP1 commented
How i can do it this ?

2019-08-30 10:32 UTC, GiantTreeLP commented
Rebase only the relevant changes onto the development branch and skip any unnecessary commits.
This might require some manual patching.

2019-08-30 11:39 UTC, MeinerLP1 commented
Fixed, and remove unnexessary commits.

2019-08-30 12:06 UTC, GiantTreeLP requested changes

2019-08-30 12:06 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> -
Why did you remove this?

2019-08-30 12:06 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +          String x = new StringBuilder("http://")
I think a round-robin approach is more fitting here.
Try each server until a request succeeds (which is usually the first one)

2019-08-30 12:06 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +    executorService.schedule(() -> {
You can use the built-in scheduler for this.

2019-08-30 12:06 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      Gson g = new Gson();
You don't need to instantiate Gson every time this command is used.
Either use a constant or a global instance.

2019-08-30 12:13 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> -
Oh its from from Patch

2019-08-30 12:16 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +          String x = new StringBuilder("http://")
How it is the best way to do that ?

2019-08-30 12:39 UTC, MeinerLP1 commented
Review pls
@GiantTreeLP

2019-08-30 12:46 UTC, GiantTreeLP requested changes

2019-08-30 12:46 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +          String x = new StringBuilder("http://")
You are still picking a random server.
Do this logic inside your asynchronous paste method and try each server until one succeeds.

2019-08-30 12:49 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +          String x = new StringBuilder("http://")
Look ich check all Server, after that i pick some random of the working Server!

2019-08-30 17:41 UTC, GiantTreeLP commented
You need to rebase your PR on the latest changes.

2019-08-30 18:42 UTC, GiantTreeLP requested changes

2019-08-30 18:42 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> +import lombok.Getter;
Please remove any traces of lombok

2019-08-30 18:46 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> +import lombok.Getter;
Ok!

2019-08-31 13:14 UTC, MeinerLP1 commented
Please look if the command ready for merge
@GiantTreeLP

2019-08-31 13:35 UTC, Sarsum commented
Please add https://paste.dsyn.ga to the list, otherwise @realPanamo might be sad

2019-08-31 13:37 UTC, Sarsum commented
Also, I think it would be great if you could either choose which PasteServer to use, or use a random one, e.g. with a Config

2019-08-31 13:41 UTC, GiantTreeLP commented
> Also, I think it would be great if you could either choose which PasteServer to use, or use a random one, e.g. with a Config

It's already configurable. But I don't like choosing a random server.
I suggested a round-robin approach or fallback approach.
So you can sort the servers by preference.

2019-08-31 15:19 UTC, MeinerLP1 commented
I can do a check on all url and use the order from the Config. Is this idea better @GiantTreeLP

2019-08-31 15:26 UTC, GiantTreeLP commented
You still don't understand fallback or round-robin.

Try to upload to the first server.  
If this fails, use the next server.  
If that one fails, use the next server.  
This goes on, until you have either a successful upload or reached the end of the list.

2019-08-31 22:52 UTC, GiantTreeLP requested changes

2019-08-31 22:52 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      HttpURLConnection connection = (HttpURLConnection) pasteUrl.openConnection();
Use try-with-resources here

2019-08-31 22:52 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +    return "KEY_NOT_FOUND";
Throw an exception and catch it properly.
Returning valid values or null is a code-smell.

2019-08-31 22:52 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      con = (HttpURLConnection) new URL(url).openConnection();
Use try-with-resources here. (Although, this method is obsolete)

2019-09-01 08:21 UTC, realPanamo commented
Hm, there are still some parts which use 2 spaces instead of 4. Would be nice if you could fix this.

2019-09-01 09:23 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      con = (HttpURLConnection) new URL(url).openConnection();
@GiantTreeLP nope, is not autocloseable

2019-09-01 09:23 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      HttpURLConnection connection = (HttpURLConnection) pasteUrl.openConnection();
@GiantTreeLP and same here, url/httpconnection is not autocloseable

2019-09-01 11:55 UTC, GiantTreeLP requested changes

2019-09-01 11:55 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      InputStream inputStream = connection.getInputStream();
Close the stream after using it.

2019-09-01 11:55 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +      con = (HttpURLConnection) new URL(url).openConnection();
Can you close it in finally though?

2019-09-01 12:15 UTC, GiantTreeLP requested changes

2019-09-01 12:15 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +				connection.disconnect();
You already disconnected the connection two lines before this.

2019-09-01 14:15 UTC, GiantTreeLP approved these changes

2019-09-01 16:19 UTC, McRuben commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandLog.java
> +			paste.append(String.format("Memory Max: %d Mb", NetworkUtils.system().getTotalPhysicalMemorySize() / 1024L)).append('\n');
You're calculating the memory as KB, but displaying it as "Mb"

2019-09-01 18:00 UTC, merged