More setup options for spigot.jar
CloudNetService/CloudNet-v2 pull request #138
Opened 2019-05-17 13:55 UTC by MeinerLP1

Add option to build newest spigot and paperspigot

2019-05-17 14:27 UTC, GiantTreeLP requested changes
This PR lacks any documentation, contains deadlocks and does not adhere to our coding style.
Additionally, there are spelling mistakes and variable names, that make no sense.

I give you a chance to redo this PR and update your code, so that it catches only errors, that are expected, doesn't lock up the system and is considered good.

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/pom.xml
> +        </dependency>
Add a specific scope

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/models/PaperMCBuild.java
> +package de.dytanic.cloudnetwrapper.models;
For the entire file: adhere to the Oracle or Google Java Codestyle

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/models/PaperMCProjectBuild.java
> +  private final String latest;
I'm pretty sure, you can deduce the latest version.
No need to store this

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/models/PaperMCProjectVersion.java
> +    this.builds = builds;
Builds is plural, PaperMCProjectBuild is singular, what is it?

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/models/SpigotVersion.java
> +  private final String path;
What does this point to?

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/models/SpigotVersion.java
> +  private final String name;
What is "name" supposed to mean?

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/setup/SetupSpigotVersion.java
> +            case "buildtools": SpigotBuilder.start(reader);
Please stick to the style that is already used in this file and break cases

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +  private static String API_URL = "https://papermc.io/api/v1/";
These should be final

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      URLConnection connection = new URL(String.format(API_PROJECT_URL,"paper")).openConnection();
"paper" seems like a constant, make it one.

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      String awnser = null;
Fix spelling mistakes

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      commandBuilder.append("java -jar ");
This is not really clean code

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +          .exec(commandBuilder.toString().split(NetworkUtils.SPACE_STRING), null, buildFolder);
Why create a string, when you just split it again.
Splitting here is unnecessary

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      while (true) {
This will never finish, because paperclip implicitly starts Paper

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    System.out.format("%s", "Spigot Version");
What?

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +      }else if(versions.stream().noneMatch(e->e.getName().equalsIgnoreCase(finalAwnser))) {
If anyMatch returns false, noneMatch has to return true

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +        /*if(rawName.endsWith(".json") && !( rawName.replace(".json","").startsWith("1.") || rawName.replace(".json","").contains("latest"))){
Remove unnecessarily commented code with no context or explanation

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    List<SpigotVersion> array = new LinkedList<>();
This is not an array

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    }catch (Exception e){
Please be specific here

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    builder.delete();
Does this recursively delete this directory?

2019-05-17 14:27 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +        commandBuilder.append("--rev "+version);
Either use the stringbuilder or don't, don't mix them

2019-05-17 14:29 UTC, GiantTreeLP requested changes

2019-05-17 14:29 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
Please check, whether a spoofed user agent is necessary and/or enough.

2019-05-17 16:03 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
Is necessary, papermc and spigot use cloudflare

2019-05-17 16:08 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    System.out.format("%s", "Spigot Version");
Prints the versions in a Table format

2019-05-17 16:09 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +      }else if(versions.stream().noneMatch(e->e.getName().equalsIgnoreCase(finalAwnser))) {
Thats wrong

2019-05-17 16:13 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
In my limited testing, the papermc api appears to not restrict plain connections, even ones with empty User-Agent or no User-Agent whatsoever: 
![image](https://user-images.githubusercontent.com/2050966/57941507-69cb3800-78cf-11e9-88a1-446f9e27e3f8.png)

2019-05-17 16:16 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
Fixed

2019-05-17 16:16 UTC, GiantTreeLP requested changes

2019-05-17 16:16 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    LinkedList<String> versions = loadVersions();
Adhere to the style guide. Use interface types.

2019-05-17 16:16 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +        System.out.println("Version not exists!");
If you are already trying to write coherent English, ask before committing wrong phrases.

This should say: "Version does not exist"

2019-05-17 16:16 UTC, MeinerLP1 commented
Where are the deadlocks?

2019-05-17 16:17 UTC, GiantTreeLP commented
Also, I have made "remarks"

2019-05-17 16:18 UTC, GiantTreeLP commented
> Where are the deadlocks?

Running Paperclip will also start a paper server.

2019-05-17 16:19 UTC, GiantTreeLP requested changes

2019-05-17 16:19 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +    System.out.format("%s", "Spigot Version");
Why are you using format, when you are just printing out an ordinary string?

2019-05-17 16:19 UTC, MeinerLP1 commented
Paperclip stops automatically the is Eula always false

2019-05-17 16:22 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      System.out.printf("%s\n", "PaperSpigot Version");
This is even more wrong than before.

2019-05-17 16:22 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      System.out.printf("%s\n", "PaperSpigot Version");
What is the right way ?

2019-05-17 16:23 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      System.out.printf("%s\n", "PaperSpigot Version");
Just use println here.
Like you are using all the time already.

2019-05-17 16:25 UTC, GiantTreeLP commented
Great, now fix the commit messages to properly reflect, what you have changed.

Good luck.

2019-05-17 16:26 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +      System.out.printf("%s\n", "PaperSpigot Version");
My idea was to print with %5s and more the date, but the split system of string cancel that

2019-05-17 16:42 UTC, MeinerLP1 commented
Where i call the method ?

2019-05-17 16:47 UTC, MeinerLP1 commented
And again isn't my code, is default code

2019-05-17 21:09 UTC, GiantTreeLP requested changes
The documentation is not fully complete.
Also: please check your PR for spelling mistakes again, there are some.
And again: Stick to the Oracle or Google Java Code Style for all of your changes, there are places where these styles are not adhered to.

2019-05-17 21:09 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/CloudNetWrapper.java
> +        Runtime.getRuntime().addShutdownHook(new Thread(this));
This is not very clean, please use a separate class for the thread.

2019-05-17 21:09 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/CloudNetWrapper.java
> +        if(PaperBuilder.exec != null) PaperBuilder.exec.destroyForcibly();
We are already using getters everywhere, stick to that.

2019-05-26 18:02 UTC, GiantTreeLP requested changes

2019-05-26 18:02 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    String API_PROJECT_VERSION_URL = "https://papermc.io/api/v1/paper/%s";
Make these strings global constants

2019-05-26 18:02 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +      System.out.println();
This is way too complicated for just writing `versions.forEach(System.out::println)`

2019-06-23 09:10 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/SpigotBuilder.java
> +      System.out.println();
Fixed in new commit

2019-06-23 09:10 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/util/PaperBuilder.java
> +    String API_PROJECT_VERSION_URL = "https://papermc.io/api/v1/paper/%s";
Fixed in new commit in PaperBuilder and SpigotBuilder

2019-06-23 09:22 UTC, realPanamo commented
Some files have a tab size of 2, this repo doesn't use that codestyle. Please use sun.

2019-06-23 09:24 UTC, MeinerLP1 commented
It's the code style file of the Project pls fix this

2019-08-30 07:23 UTC, TheMeinerLP reviewed
All requested changes have been reviewed and edited

2019-08-30 09:43 UTC, GiantTreeLP commented
This looks okay. It would be great, if you'd add the latest Minecraft versions (1.14 - 1.14.4) to the selection.

2019-08-30 09:48 UTC, MeinerLP1 commented
To the build tools or what ?

2019-08-30 12:38 UTC, MeinerLP1 commented
Finish, ready to merge

2019-08-30 12:42 UTC, GiantTreeLP requested changes

2019-08-30 12:42 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                .exec("java -jar pa perclip.jar", null, buildFolder);
Are you sure that the file is called `pa` and requires `perclip.jar` as an argument?

2019-08-30 12:55 UTC, MeinerLP1 commented
Fixed little issue, thx @GiantTreeLP !

2019-08-30 13:29 UTC, MeinerLP1 commented
I think is now ready to merge!
@GiantTreeLP sorry for extra work!

2019-08-31 12:20 UTC, MeinerLP1 commented
@GiantTreeLP Think ready to merge for 2.1.16 or 2.1.17

2019-08-31 12:43 UTC, GiantTreeLP commented
![image](https://user-images.githubusercontent.com/2050966/64064085-a6f8d300-cbfd-11e9-8835-ac4bb5b01b5e.png)

Can you add a bit more feedback to the user about what they have to do here?

2019-08-31 12:46 UTC, MeinerLP1 commented
You mean like select version and stuff 😅

2019-08-31 12:47 UTC, GiantTreeLP commented
> You mean like select version and stuff 😅

Correct. Just so the user knows, why the wrapper has seemingly stopped.

2019-08-31 13:14 UTC, MeinerLP1 commented
I added some message for the user
Please checkout the new version.
Merge the pull request you think is ready @GiantTreeLP ;)

2019-09-01 12:12 UTC, GiantTreeLP requested changes

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +            System.out.println("Available PaperSpigot Versions");
```suggestion
            System.out.println("Available Paper Versions:");
```

It's not called PaperSpigot officially.

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +            System.out.println("PaperSpigot Version");
Just remove those three lines.

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                    System.out.println("Version does not exist!");
```suggestion
                    System.out.println("This version does not exist!");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                System.out.println("Copy spigot.jar");
```suggestion
                System.out.println("Copying spigot.jar");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +        System.out.println("Fetch Builds");
```suggestion
        System.out.println(String.format("Fetching build %s", version));
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +        System.out.println("Download PaperClip");
```suggestion
        System.out.println("Downloading Paperclip");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +        System.out.println("Build finish!");
```suggestion
        System.out.println("Build finished!");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +        System.out.println("Copy spigot.jar");
```suggestion
        System.out.println("Copying spigot.jar");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SetupSpigotVersion.java
> +		System.out.println("Choose a minecraft server version [\"paper\",\"spigot\", \"buildtools\"]");
```suggestion
		System.out.println("Choose a minecraft server version [\"paper\", \"spigot\", \"buildtools\"]");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +        System.out.println("Fetch Spigot Versions");
```suggestion
        System.out.println("Fetching Spigot versions");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +        System.out.println("Available Spigot Versions");
```suggestion
        System.out.println("Available Spigot versions:");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +        System.out.println("Spigot Version\n");
As with paper: remove those three lines

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +                System.out.println("Version does not exist!");
```suggestion
                System.out.println("This version does not exist!");
```

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +                if (!(rawName.contains("latest.json") | rawName.startsWith("1."))) {
```suggestion
                if (!(rawName.contains("latest.json") || rawName.startsWith("1."))) {
```

Please use logical expressions when dealing with booleans (short-circuiting)

2019-09-01 12:12 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/SpigotBuilder.java
> +                System.out.println("Copy spigot.jar");
```suggestion
                System.out.println("Copying spigot.jar");
```

2019-09-01 20:06 UTC, MeinerLP1 commented
Finally version. Please review!
@GiantTreeLP 
@byRoadrunner

2019-09-01 20:34 UTC, GiantTreeLP requested changes

2019-09-01 20:34 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			while (inputStream.read() != -1) {
`read()` returns the read byte.

Use the following, optimized construct for this:

```java
byte[] buffer = new byte[1024];
int length = 0;
while ((length = inputStream.read(buffer)) != -1) {
    // output here
}
```

2019-09-01 20:38 UTC, MeinerLP1 commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			while (inputStream.read() != -1) {
Is the length useful?

2019-09-01 20:38 UTC, MeinerLP1 commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			while (inputStream.read() != -1) {
I do nothing with the lenght!

2019-09-02 09:49 UTC, MeinerLP1 commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			while (inputStream.read() != -1) {
Fixed!

2019-09-02 10:05 UTC, MeinerLP1 commented
@GiantTreeLP Please review the code!

2019-09-02 12:05 UTC, GiantTreeLP requested changes

2019-09-02 12:05 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                    > 0) {
You use this file multiple times, extract it into a variable.

2019-09-02 12:05 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			this.countDownLatch.countDown();
I would actually do this in a finally block.
This way you can be sure, that an error doesn't lock up the waiting thread.

2019-09-02 12:07 UTC, MeinerLP1 commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			this.countDownLatch.countDown();
Should i close the stream ?

2019-09-02 12:09 UTC, MeinerLP1 commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                    > 0) {
Is not the same code on different methods

2019-09-02 12:10 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			this.countDownLatch.countDown();
Actually, yes, countDown and close both belong to the finally block

2019-09-02 12:11 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/spigot/PaperBuilder.java
> +                    > 0) {
Then why to you check for paperclip, when you need/want paper, though?

2019-09-02 12:28 UTC, MeinerLP1 commented
I change dublicated code and improve the code
@GiantTreeLP

2019-09-02 12:57 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			this.countDownLatch.countDown();
You did not count down in the finally block.
You only closed the InputStream

2019-09-02 13:19 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java
> +			this.countDownLatch.countDown();
I don't want to discourage you, but as it stands, this code is broken. It will count down twice, once here and once in the finally block.

2019-09-02 14:23 UTC, MeinerLP1 commented
@GiantTreeLP

2019-09-02 14:23 UTC, merged