Cleaned up some code from gameserver class on bootstrap method.
CloudNetService/CloudNet-v2 pull request #248
Opened 2020-03-20 15:56 UTC by MeinerLP1

Split some massiv code into smaller methodes from massiv bootstrap method.
And also add java documentation to the splitted methods. 
A rework is planned to the future of 2.2.0/1. This is only a pr for improve legibility of the class.

2020-03-22 16:35 UTC, GiantTreeLP requested changes
I don't need to write anything about your English...
Note that the changes I requested do not exclude similar issues, I just noted each change once instead of everywhere.

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        try (InputStreamReader inputStreamReader = new InputStreamReader(Files.newInputStream(Paths.get(path + "/server.properties")))) {
Use the separator-less version of `Paths.get` by specifying each directory separately
```suggestion
        try (InputStreamReader inputStreamReader = new InputStreamReader(Files.newInputStream(Paths.get(path,  "server.properties")))) {
```

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +    private ServerInfo configureNoGlowstoneServer() {
Choose a more fitting name, this code does not deal with Glowstone, so Glowstone has no place in the name.

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * @return Return the finish Server info.
```suggestion
     * @return the finished server info of the configured server.
```

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * Configure a server like not a glowstone server type.
This has nothing to do with Glowstone, focus on what this method does, not what it does not.

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            try (OutputStreamWriter outputStreamWriter = new OutputStreamWriter(Files.newOutputStream(Paths.get(path + "/config/glowstone.yml")),
You can use the `Writer` interface here

2020-03-22 16:35 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +                System.err.println("Filled empty server.properties (or missing \"max-players\" entry) of server [" + this.serverProcess.getMeta()
Either use the logger here or ask yourself whether this is actually an error.
This situation is perfectly fine and I think the server can handle incomplete properties.

2020-04-01 15:47 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            try (OutputStreamWriter outputStreamWriter = new OutputStreamWriter(Files.newOutputStream(Paths.get(path + "/config/glowstone.yml")),
Comming soon :)

2020-04-01 16:41 UTC, GiantTreeLP requested changes
In addition to the comments, please reformat the file properly.

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        switch (plugin.getPluginResourceType()) {
You are allowed to use `if` statements here, the `switch` makes this part harder to read.

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            Files.deleteIfExists(Paths.get(path + "/plugins/CloudNetAPI.jar"));
Use the varargs to your advantage
```suggestion
            Files.deleteIfExists(Paths.get(path, "plugins", "CloudNetAPI.jar"));
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            if (!Files.exists(Paths.get(path + "/config"))) {
```suggestion
            if (!Files.exists(Paths.get(path, "config"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +                    Files.createDirectories(Paths.get(path + "/config"));
```suggestion
                    Files.createDirectories(Paths.get(path, "config"));
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            if (!Files.exists(Paths.get(path + "/config/glowstone.yml"))) {
```suggestion
            if (!Files.exists(Paths.get(path, "config", "glowstone.yml"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        if (!Files.exists(Paths.get(path + "/server.properties"))) {
```suggestion
        if (!Files.exists(Paths.get(path, "server.properties"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        if (!Files.exists(Paths.get(path + "/bukkit.yml"))) {
```suggestion
        if (!Files.exists(Paths.get(path, "bukkit.yml"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        if (!Files.exists(Paths.get(path + "/spigot.yml"))) {
```suggestion
        if (!Files.exists(Paths.get(path, "spigot.yml"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            this.serverInfo = configureNonNormalServer();
You are free to create proper methods for all server group types.

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
>          if (!Files.exists(Paths.get(path + "/CLOUD"))) {
```suggestion
        if (!Files.exists(Paths.get(path, "CLOUD"))) {
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +                Files.createDirectory(Paths.get(path + "/CLOUD"));
```suggestion
                Files.createDirectory(Paths.get(path, "CLOUD"));
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
```suggestion
                                                                                                                                           .get(
                                                                                                                                               path, "CLOUD", "connection.json"));

```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            try (Writer outputStreamWriter = new OutputStreamWriter(Files.newOutputStream(Paths.get(path, "/config/glowstone.yml")),
```suggestion
            try (Writer writer = new OutputStreamWriter(Files.newOutputStream(Paths.get(path, "config", "glowstone.yml")),
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +                ConfigurationProvider.getProvider(YamlConfiguration.class).save(configuration, outputStreamWriter);
```suggestion
                ConfigurationProvider.getProvider(YamlConfiguration.class).save(configuration, writer);
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +                properties.load(inputStreamReader);
```suggestion
        try (Reader reader = new InputStreamReader(Files.newInputStream(Paths.get(path,  "server.properties")))) {
            try {
                properties.load(reader);
```

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * @throws Exception Throws some exception, if something wrong on the start of a game server
Please check this definition again and be more specific

2020-04-01 16:41 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
>      private void startProcess() throws Exception {
Is there no more specific exception being thrown?

2020-04-01 16:45 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
>      private void startProcess() throws Exception {
Nope, alltime the same no specific.

2020-04-01 16:47 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            this.serverInfo = configureNonNormalServer();
But we have only four, but do all times the same thing

2020-04-01 17:25 UTC, GiantTreeLP requested changes
Just fix the format, use the logger everywhere instead of System.out and we should be done.

2020-04-01 17:25 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +            this.serverInfo = configureNonNormalServer();
Then reverse the condition and only treat Glowstone specially.

2020-04-01 17:30 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * @throws Exception Throws some exception, if something wrong on the start of a game server
Cannot make specific

2020-04-01 17:46 UTC, GiantTreeLP commented
Please test these changes (including downloading plugins from the master and a url) and add documentation.

After this I am sure we can merge this

2020-04-01 17:47 UTC, MeinerLP1 commented
Ok, i can do this

2020-04-01 19:55 UTC, MeinerLP1 commented
Test Passed:
- [X] Download Plugin from URL(ProtocolSupport from CI)
- [X] Download Master Template
- [X] Download URL Template

2020-04-02 07:17 UTC, derklaro requested changes

2020-04-02 07:17 UTC, derklaro commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * Download the {@link ServerInstallablePlugin] an copy to a web plugin cache.
I think here is a typo (an copy to a web...)

2020-04-02 07:17 UTC, derklaro commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * @return Given back a complete server info
Given back is redundant here

2020-04-02 07:17 UTC, derklaro commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        serverProcess.setServerStage(ServerStage.PROCESS);
I think if this is removed not a bag of rice will fall over in China (This is just set and then immediately changed again...)

2020-04-02 12:52 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +        serverProcess.setServerStage(ServerStage.PROCESS);
Added to my to-do!

2020-04-12 15:36 UTC, MeinerLP1 commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java
> +     * @return Given back a complete server info
No, is used from parent method.

2020-04-15 16:39 UTC, merged