Extraction of modules from main cloud
CloudNetService/CloudNet-v2 pull request #259
Opened 2020-04-13 15:09 UTC by MeinerLP1

This pull request, removes some modules(CloudPerms, NPC Selector, SignSystem, SimpleNameTags, CloudFlare, NotifySystem) from main cloud. The idea to rebuild the modules in external reposetories and use later teh rest api of updateserver with a install command to install the modules.

Please feel free to review and say what can i improve. I try my best to clean up some code

2020-04-24 08:04 UTC, GiantTreeLP requested changes

2020-04-24 08:04 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> +        Paths.get("groups")
You can leave in the "modules" directory, even if it is left empty.

2020-04-24 08:04 UTC, GiantTreeLP commented on cloudnet-core/src/main/resources/modules/modules.properties
> +#
You may delete this file

2020-04-24 13:44 UTC, MeinerLP1 commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java
> +        Paths.get("groups")
Look in the module manager, there are becomes to create the folder

2020-04-24 13:44 UTC, MeinerLP1 commented on cloudnet-core/src/main/resources/modules/modules.properties
> +#
I deleted the file

2020-04-25 20:32 UTC, GiantTreeLP commented
Will be merged once all modules are in development branches of their separate repositories.

2020-05-01 11:07 UTC, GiantTreeLP commented
> Will be merged once all modules are in development branches of their separate repositories.

Push

2020-05-13 20:26 UTC, merged