Complete revision of the module system
CloudNetService/CloudNet-v2 pull request #277
Opened 2020-06-07 20:59 UTC by TheMeinerLP

In this Pull Request the complete module system was revised. Circular dependencies should no longer be a problem in the future. Also an extended API was made available to allow developers to better integrate the system. It was built very similar to Bukkit and the Spigot API. 

Missing functions are the Observe Pattern for Auto Update and the Event for FileDeployment into the Cloud.

Also the CloudAPI load bug was fixed because of the renaming of the pack.
And there are a few places where an improved exception handling was done.

And yes, the code needs to be more ordered or made more beautiful and also the description needs to be added.

2020-06-07 21:01 UTC, TheMeinerLP commented
The loading of the modules was tested. 
Here are the three example jar to test.

The order should be as follows:
- ParentExampleModuleTwo  
- ParentExampleModule
- ExampleModuleTwo

2020-06-07 21:01 UTC, TheMeinerLP commented
[modules.zip](https://github.com/CloudNetService/CloudNet/files/4742967/modules.zip)

2020-06-07 21:13 UTC, GiantTreeLP requested changes
There are a few more changes I may have missed to mark.
All in all not bad, a few things should be done differently though, in order to reduce coupling of classes and improving cohesion (https://sites.google.com/site/koesterprogramming/home/softwareentwicklung/kohaesion-und-kopplung)

2020-06-07 21:13 UTC, GiantTreeLP commented on cloudnet-api/cloudnet-api-bridge/src/main/resources/plugin.yml
> +author: cloudNetService
Fix typo

2020-06-07 21:13 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/ModuleClassLoader.java
> +        javaCloudModule.init(this.loader,this.description);
This is bad application design.
The class loader should only care about classes and should never be used for any kind of initialization routine.
Move this code into the module manager and make it part of the Module interface.

2020-06-07 21:13 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/model/CloudModuleDescriptionFile.java
> +                                      HashSet<CloudModuleDependency> dependencies,
Use interface types here (Set)

2020-06-07 21:13 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/model/CloudModuleDescriptionFile.java
> +        CloudModuleDescriptionFile thisClazz = Document.GSON.fromJson(new InputStreamReader(stream), TypeToken.get(CloudModuleDescriptionFile.class).getType());
Make the TypeToken/Type a constant

2020-06-07 21:13 UTC, GiantTreeLP commented on pom.xml
> +        <dependency.slf4j.version>2.0.0-alpha1</dependency.slf4j.version>
Is an alpha version really good here?

2020-06-07 21:16 UTC, TheMeinerLP commented on pom.xml
> +        <dependency.slf4j.version>2.0.0-alpha1</dependency.slf4j.version>
Is the last public version that seems stable. A few versions before that caused problems with the logger

2020-06-08 06:46 UTC, derklaro requested changes

2020-06-08 06:46 UTC, derklaro commented on cloudnet-cord/cloudnet-log/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +            e.printStackTrace();
If the reader cannot get initialized you should throw the exception instead of just catching it (will cause null-problems in the next line)

2020-06-08 06:46 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
I think module name is not the best choice here

2020-06-08 06:46 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/exception/InvalidDescriptionException.java
> +    public InvalidDescriptionException() { }
We never do that - please break the line 
```
public InvalidDescriptionException() {
}
```

2020-06-08 06:46 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/model/CloudModuleDescriptionFile.java
> +    //transient allows to use this constant only on runtime and was not saved into a config
Fix the english or remove 😄

2020-06-08 06:46 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +        modules = new LinkedHashMap<>();
Duplicate modules? I think this might break some code and is definitely not useful at all

2020-06-08 08:42 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
Why? The drawing is already correct, because it is used for the module and it shows clearly if the user is using this logger. That exactly this module with the name. That has written

2020-06-08 08:43 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +        modules = new LinkedHashMap<>();
Was an old description

2020-06-08 08:43 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
Because it's not the name of the module it's wrapped

2020-06-08 08:48 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
It is the name, you are wrong

2020-06-08 08:49 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
`this.moduleName = "[" + module.getModuleJson().getName() + "] ";`

2020-06-08 08:50 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +    private final String moduleName;
It is wrapped not just the module name

2020-06-08 10:37 UTC, TheMeinerLP commented
All things from issue #270  were made.

2020-06-08 11:08 UTC, TheMeinerLP commented
Also issue #265  is closed or chopped off

2020-06-08 13:25 UTC, GiantTreeLP requested changes

2020-06-08 13:25 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +                                if (migrateCloudModule.migrate(module.getModuleJson().getVersion(),
There should be an else branch here

2020-06-08 13:25 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +                                optionalJavaCloudModule.ifPresent(value -> {
There should be an orElse branch here

2020-06-08 13:25 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/MigrateCloudModule.java
> +    boolean migrate(String oldVersion, String newVersion);
You should be able to use semver here

2020-06-08 13:32 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/model/CloudModuleDescriptionFile.java
> +    public static transient TypeToken<CloudModuleDescriptionFile> CLOUD_MODULE_DESCRIPTION_FILE = TypeToken.get(CloudModuleDescriptionFile.class);
```suggestion
    public static final transient Type CLOUD_MODULE_DESCRIPTION_FILE = TypeToken.get(CloudModuleDescriptionFile.class).getType();
```

2020-06-08 13:32 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/model/CloudModuleDescriptionFile.java
> +        CloudModuleDescriptionFile thisClazz = Document.GSON.fromJson(new InputStreamReader(stream), CLOUD_MODULE_DESCRIPTION_FILE.getType());
```suggestion
        CloudModuleDescriptionFile thisClazz = Document.GSON.fromJson(new InputStreamReader(stream), CLOUD_MODULE_DESCRIPTION_FILE);
```

2020-06-08 14:57 UTC, GiantTreeLP requested changes

2020-06-08 14:57 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-log/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +    private ConsoleReader reader;
Why have these lost the final qualifier?

2020-06-08 14:57 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-log/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +    private Handler loggingHandler;
Why have these lost the final qualifier?

2020-06-08 14:57 UTC, GiantTreeLP commented on cloudnet-cord/cloudnet-web/src/main/java/eu/cloudnetservice/cloudnet/v2/web/server/WebServer.java
> +            e.initCause(new RuntimeException("Cannot bind REST-API to the given port " + port + " and host " + address));
I hope you made sure, that ALL exceptions, which are used like this, fulfill the requirements: https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#initCause(java.lang.Throwable)

Does this print the exception though? It does not seem like it does, so this exception and probably a lot of others are effectively ignored.

2020-06-08 14:57 UTC, GiantTreeLP commented on pom.xml
> +        <dependency.slf4j.version>2.0.0-alpha1</dependency.slf4j.version>
Please test again with version 1.7.30

2020-06-08 15:00 UTC, TheMeinerLP commented on cloudnet-cord/cloudnet-log/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +    private ConsoleReader reader;
This is about the try and catch block

2020-06-08 15:00 UTC, TheMeinerLP commented on cloudnet-cord/cloudnet-log/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +    private Handler loggingHandler;
This is about the try and catch block

2020-06-08 15:25 UTC, TheMeinerLP commented
[modules.zip](https://github.com/CloudNetService/CloudNet/files/4746908/modules.zip)
Reworked module files

2020-06-08 16:28 UTC, GiantTreeLP requested changes

2020-06-08 16:28 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/ModuleClassLoader.java
> +        if (name.startsWith("org.bukkit.") || name.startsWith("net.minecraft.")) {
This can never happen.
And even if it does, we don't care.

2020-06-08 18:15 UTC, GiantTreeLP requested changes

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleLogger.java
> +     * @param module is used to say in the log message that this message comes from this module
```suggestion
     * @param module used to refer to the module in messages.
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Looks for files in the modules and update folder and indexes all files.
     * Afterwards all modules are loaded and checked, whether updates are available and whether migrations need to be run.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Unloads the given module.
     * If it is currently enabled, disables the module and unloads all known classes.
     * @param module the module that should be unloaded.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Disables the module and unloads all classes from the module.
     * @param module the module that should be disabled.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Checks a module's dependencies and attempts to load a module.
     * If a dependency is not present or incompatible with the module, this will disable and unload the module cleanly.
     * @param module the module that should be loaded.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
>      private void handleLoaded(final List<Path> toLoaded, final List<Path> toUpdate) {
```suggestion
    /**
     * Loads all given modules, checks those for updates and runs migrations, if necessary.
     * @param toLoad contains all files that will be loaded.
     * @param toUpdate contains all update files which will be checked and applied.
     */
    private void handleLoaded(final List<Path> toLoad, final List<Path> toUpdate) {
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Attempts to load a module from the given path.
     
     * @param path the place where the module resides.
     * @return an {@code Optional} containing the loaded module, if successful.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Attempts to read and parse a module's description file.
     
     * @param module the path where the module resides.
     
     * @return an {@code Optional} possibly containing the parsed description file.
     */
```

Please add appropriate throws declarations

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Checks whether the given path is present in the list of modules to load.
     * The check is done using the absolute path.
     
     * @param path the path to the module.
     * @param toLoad a list of all modules already indexed.
     * @return {@code true}, if the module is present in the list, {@code false} otherwise.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Attempts to the a class by the given name.
     * Searches every modules' class loaders.
     *
     * @param name the fully-qualified name of the class.
     * @return the class, if present in any class loader. {@code null}, if the class is not present in any search class loader.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
>      void setClass(final String name, final Class<?> clazz) {
```suggestion
    /**
     * Adds the class to a list of classes using the given name.
     * @param name the name that the given class should be identified with. 
     * @param clazz the class to be added.
     */
    void addClass(final String name, final Class<?> clazz) {
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Removes a class from the cache by the given name.
     * @param name the name of the class to remove.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * @return a map of loaded modules' names mapped to the respective module instances.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
>          return Optional.of(getModules().get(name));
Have you tested this with non-existent module names?

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Returns the module instance associated to the given name, if present.
     * @param name the name of the module to get.
     * @return an {@code Optional} possibly containing the module's instance.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Resolves all dependencies of the given module description files recursively.
     * @param cloudModuleDescriptionFiles a list containing the dependencies to be resolved.
     * @param javaCloudModule the module for which to resolve the dependencies.
     * @return a list of modules that the given module depends on in the order they need to be loaded.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
```suggestion
    /**
     * Resolves dependencies recursively.
     * @param cloudModuleDescriptionFiles a list containing the dependencies which should be resolved.
     * @return a list of modules in the order they need to be loaded.
     */
```

2020-06-08 18:15 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +     */
I don't have a suggestion for this one, but the documentation given seems to be incomplete or does not match, what I understand from this code.

2020-06-09 18:44 UTC, GiantTreeLP requested changes

2020-06-09 18:44 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> + * Manages loading of modules, dependencies, updating, mirroring and unloading of modules.
> mirroring

Mirroring? I believe this should be migrating. And if that is so, then `running migrations`.

2020-06-10 08:46 UTC, derklaro requested changes

2020-06-10 08:46 UTC, derklaro commented on cloudnet-examples/src/main/java/eu/cloudnetservice/cloudnet/v2/examples/module/ExampleModuleCommand.java
> +    /**
I think this description is a little bit mislocated

2020-06-10 08:46 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/CloudConfig.java
> +                Files.createDirectories(path);
This is not a good idea - if something goes wrong here all other file inserts in the directory will fail, too

2020-06-10 08:53 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/CloudConfig.java
> +                Files.createDirectories(path);
Tell me a better way than before like everybody else?

2020-06-10 11:31 UTC, derklaro approved these changes
LGTM

2020-06-10 17:40 UTC, GiantTreeLP approved these changes

2020-06-10 17:40 UTC, GiantTreeLP commented
Alright, merging.

Keep in mind that all modules need to be adapted to this new API.

2020-06-10 17:41 UTC, merged