WIP:
CloudNetService/CloudNet-v2 pull request #289
Opened 2020-06-29 08:59 UTC by TheMeinerLP

This pull request includes:

- [X] breaking changes
- [ ] no breaking changes

### Changes made to the repository:

- Added a console module to manage console inputs 
- A dynamic console registry was implemented
- WIP: Passwords can now be entered hidden in the console
- Command inputs like CTRL+C can be intercepted.
- JLine3 was used as basis
- A command history was implemented
- An automatic command completion was implemented
- Commands can be highlighted

### Documentation of test results:

- Tests have not yet been carried out, as it is still in development

### Related issues/discussions:

This Pull Request is a part of issue #279

2020-06-29 12:27 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +    private boolean running;
Codacy found an issue: [Avoid unused private fields such as 'running'.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-06-29 12:27 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-06-29 12:27 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +    private boolean running;
Codacy found an issue: [Perhaps 'running' could be replaced by a local variable.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-06-29 12:27 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-06-29 12:27 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +    private LineReader lineReader;
Codacy found an issue: [Avoid unused private fields such as 'lineReader'.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 55
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  5
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +    override fun format(record: LogRecord?): String {
Codacy found an issue: [NestedBlockDepth - 4/4 - [format] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:13:18](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java
> +                                if (setupComplete != null) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    private final ConsoleRegistry consoleRegistry;
Codacy found an issue: [Perhaps 'consoleRegistry' could be replaced by a local variable.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java
> +import java.util.Collection;
Codacy found an issue: [Avoid unused imports such as 'java.util.Collection'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +class LoggingFormatter : Formatter() {
Codacy found an issue: [UndocumentedPublicClass - [LoggingFormatter] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:11:7](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +import java.io.OutputStreamWriter;
Codacy found an issue: [Avoid unused imports such as 'java.io.OutputStreamWriter'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java
> +import eu.cloudnetservice.cloudnet.v2.setup.SetupResponseType;
Codacy found an issue: [Unused import - eu.cloudnetservice.cloudnet.v2.setup.SetupResponseType.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +import net.md_5.bungee.config.Configuration;
Codacy found an issue: [Avoid unused imports such as 'net.md_5.bungee.config.Configuration'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +import net.md_5.bungee.config.YamlConfiguration;
Codacy found an issue: [Avoid unused imports such as 'net.md_5.bungee.config.YamlConfiguration'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java
> +    private final String version, url;
Codacy found an issue: [Use one line for each declaration, it enhances code readability.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +import eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper;
Codacy found an issue: [Unused import - eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java
> +import eu.cloudnetservice.cloudnet.v2.setup.SetupResponseType;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.setup.SetupResponseType'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +import java.nio.charset.StandardCharsets;
Codacy found an issue: [Avoid unused imports such as 'java.nio.charset.StandardCharsets'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java
> +import java.util.ArrayList;
Codacy found an issue: [Unused import - java.util.ArrayList.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +        switch (spigotType) {
Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +import java.util.stream.Collectors;
Codacy found an issue: [Unused import - java.util.stream.Collectors.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java
> +import java.util.function.Predicate;
Codacy found an issue: [Unused import - java.util.function.Predicate.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +    private Terminal terminal;
Codacy found an issue: [Perhaps 'terminal' could be replaced by a local variable.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +import java.nio.file.Files;
Codacy found an issue: [Avoid unused imports such as 'java.nio.file.Files'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +import eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].toLowerCase().equals("create")) {
Codacy found an issue: [Using equalsIgnoreCase() is cleaner than using toUpperCase/toLowerCase().equals().](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 10:22 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +import java.util.stream.Collectors;
Codacy found an issue: [Avoid unused imports such as 'java.util.stream.Collectors'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:18 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 14
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +    override fun format(record: LogRecord?): String {
Codacy found an issue: [NestedBlockDepth - 4/4 - [format] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:13:18](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java
> +    static void printProcessOutputToConsole(Process exec) {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +        switch (spigotType) {
Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/CloudNetWrapperConfigSetup.java
> +        setupCancel(() -> System.exit(-1));
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java
> +                                if (setupComplete != null) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +        switch (input.toLowerCase()) {
Codacy found an issue: [A switch statement does not contain a break](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +class LoggingFormatter : Formatter() {
Codacy found an issue: [UndocumentedPublicClass - [LoggingFormatter] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:11:7](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    private final SignalManager signalManager;
Codacy found an issue: [Perhaps 'signalManager' could be replaced by a local variable.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 12:19 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    private final ConsoleRegistry consoleRegistry;
Codacy found an issue: [Perhaps 'consoleRegistry' could be replaced by a local variable.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 7
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +class LoggingFormatter : Formatter() {
Codacy found an issue: [UndocumentedPublicClass - [LoggingFormatter] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:11:7](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 14:28 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +    override fun format(record: LogRecord?): String {
Codacy found an issue: [NestedBlockDepth - 4/4 - [format] at /src/cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt:13:18](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:23 UTC, GiantTreeLP requested changes
This PR is still in draft, so this is a preliminary review.

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +            String[] a = line.split(" ");
what is `a` supposed to mean?

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                      .forEach(strings::add);
This can be written in a more simple form, by extracting the condition from `testString` (what ever that is supposed to be) out of this stream, which is not necessary.

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.kt
> +class CloudLogger : Logger("CloudLogger",null) {
Add proper documentation

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/pom.xml
> +            <artifactId>kotlin-stdlib</artifactId>
Do we really require kotlin in this module and if so, why not use it exclusively?

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/kotlin/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.kt
> +        val builder = StringBuilder()
use the `buildString` method

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDebug.java
> +        CloudNet.getLogger().setDebugging(!CloudNet.getLogger().getDebugging());
Why did you rename the boolean getters?

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java
> -                        }
Why did you delete this safeguard?

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java
> +    ;
You could have added 1.16, 1.16.1 and 1.16.2

2020-08-25 15:23 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java
> +                                 "1.15.2");
You could have added additional versions

2020-08-25 15:23 UTC, GiantTreeLP commented on pom.xml
> +        <kotlin.version>1.3.72</kotlin.version>
Please use up-to-date versions of libraries.

2020-08-25 15:26 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 7
           

Complexity increasing per file
==============================
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:26 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:31 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 15:31 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:31 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:31 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:31 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:31 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:36 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java
> -                        }
I have deleted the local wrapper

2020-08-25 15:37 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 15:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 15:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                        if (argument.toLowerCase().contains(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:12 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:33 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-25 16:33 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:33 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                        if (argument.toLowerCase().contains(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:33 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:33 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:34 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-25 16:34 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 8
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  3
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/model/LoggingOutputStream.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].equalsIgnoreCase("wrapper")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-26 20:20 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                        if (argument.toLowerCase().contains(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 32
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java  4
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  8
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
         

Clones added
============
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandShutdown.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 321, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 377, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +import eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper;
Codacy found an issue: [Unused import - eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +import org.jline.reader.impl.DefaultParser;
Codacy found an issue: [Avoid unused imports such as 'org.jline.reader.impl.DefaultParser'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].equalsIgnoreCase("wrapper")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 459, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +import org.jline.reader.impl.DefaultParser;
Codacy found an issue: [Unused import - org.jline.reader.impl.DefaultParser.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Unused import - java.util.logging.ConsoleHandler.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandInfo.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java
> +            if (candidateCollection != null || candidateCollection.size() > 0) {
Codacy found an issue: [Method call on object which may be null](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Avoid unused imports such as 'java.util.logging.ConsoleHandler'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Avoid unused imports such as 'org.fusesource.jansi.Ansi'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Avoid unused imports such as 'java.util.logging.ConsoleHandler'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:37 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Unused import - org.fusesource.jansi.Ansi.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:38 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 32
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  8
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
         

Clones added
============
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java
> +            if (candidateCollection != null || candidateCollection.size() > 0) {
Codacy found an issue: [Method call on object which may be null](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Unused import - org.fusesource.jansi.Ansi.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 377, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +import org.jline.reader.impl.DefaultParser;
Codacy found an issue: [Unused import - org.jline.reader.impl.DefaultParser.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Unused import - java.util.logging.ConsoleHandler.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +import eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.master.setup.SetupWrapper'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                        if (argument.value().toLowerCase().contains(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 459, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Avoid unused imports such as 'java.util.logging.ConsoleHandler'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream;
Codacy found an issue: [Unused import - eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Avoid unused imports such as 'java.util.logging.ConsoleHandler'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Unused import - java.util.logging.ConsoleHandler.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandShutdown.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 321, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java
> +    private static final ReplacementSpecification[] REPLACEMENTS = new ReplacementSpecification[]
Codacy found an issue: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Avoid unused imports such as 'org.fusesource.jansi.Ansi'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:39 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandInfo.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 32
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  8
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  3
         

Complexity decreasing per file
==============================
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -6
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
         

Clones added
============
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Avoid unused imports such as 'org.fusesource.jansi.Ansi'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 377, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Avoid unused imports such as 'java.util.logging.ConsoleHandler'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandShutdown.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 321, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java
> +            if (candidateCollection != null || candidateCollection.size() > 0) {
Codacy found an issue: [Method call on object which may be null](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream;
Codacy found an issue: [Avoid unused imports such as 'eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Unused import - java.util.logging.ConsoleHandler.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].equalsIgnoreCase("wrapper")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:43 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +import org.jline.reader.impl.DefaultParser;
Codacy found an issue: [Avoid unused imports such as 'org.jline.reader.impl.DefaultParser'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 459, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Unused import - org.fusesource.jansi.Ansi.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import java.util.logging.ConsoleHandler;
Codacy found an issue: [Unused import - java.util.logging.ConsoleHandler.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +import org.jline.reader.impl.DefaultParser;
Codacy found an issue: [Unused import - org.jline.reader.impl.DefaultParser.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +import eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream;
Codacy found an issue: [Unused import - eu.cloudnetservice.cloudnet.v2.logging.LoggingOutputStream.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java
> +    private static final ReplacementSpecification[] REPLACEMENTS = new ReplacementSpecification[]
Codacy found an issue: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-27 17:44 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:57 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 26
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java  4
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java  3
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/stream/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java  19
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/packet/out/PacketOutConsoleSettings.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  3
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java  17
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  5
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/network/packet/in/PacketInConsoleSettings.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  4
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -4
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
         

Clones added
============
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/packet/in/PacketInAuthHandler.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java  1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    public static String replaceAnsi(String string) {
Codacy found an issue: [Avoid reassigning parameters such as 'string'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandInfo.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public void onExecuteCommand(final CommandSender sender, final ParsedLine parsedLine, final String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +            switch (args[0].toLowerCase()) {
Codacy found an issue: [A switch statement does not contain a break](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 459, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public List<Candidate> onTab(final long argsLength, final String lastWord, final ParsedLine parsedLine, final String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    public static String replaceAnsiWithoutReset(String string) {
Codacy found an issue: [Avoid reassigning parameters such as 'string'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +public class AnsiColorReplacer {
Codacy found an issue: [The utility class name 'AnsiColorReplacer' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandShutdown.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 321, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Unused import - java.io.IOException.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/CloudConfig.java
> +        String hostName = NetworkUtils.getHostName();
Codacy found an issue: [Avoid unused local variables such as 'hostName'.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Unused import - org.fusesource.jansi.Ansi.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                    if (argument.value().toLowerCase().startsWith(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java
> +import org.fusesource.jansi.Ansi;
Codacy found an issue: [Avoid unused imports such as 'org.fusesource.jansi.Ansi'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].equalsIgnoreCase("wrapper")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/JLine3ConsoleHandler.java
> +    private static final ReplacementSpecification[] REPLACEMENTS = new ReplacementSpecification[]
Codacy found an issue: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 377, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 16:58 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:07 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 19
           

Complexity increasing per file
==============================
- cloudnet-app-lib/cloudnet-setup/src/main/java/eu/cloudnetservice/cloudnet/v2/setup/Setup.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SetupSpigotVersion.java  6
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java  5
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleRegistry.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/CloudLogger.java  2
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/handler/ColoredConsoleHandler.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java  5
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/PaperBuilder.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java  17
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/stream/LoggingOutputStream.java  3
- cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/network/packet/in/PacketInConsoleSettings.java  4
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/packet/out/PacketOutConsoleSettings.java  1
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java  1
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java  3
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java  3
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java  6
- cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java  4
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/SignalManager.java  2
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java  1
- cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/completer/CloudNetCompleter.java  19
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandSetup.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -20
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java  -4
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandDelete.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandClear.java  -1
+ cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java  -2
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/bootstrap/CloudBootstrap.java  -5
         

Clones added
============
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/packet/in/PacketInAuthHandler.java  1
- cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java  1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472&bid=18894034)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +            if (args[0].equalsIgnoreCase("screen")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandWrapper.java
> +            if (args[0].equalsIgnoreCase("wrapper")) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    private static final ReplacementSpecification[] REPLACEMENTS = new ReplacementSpecification[]
Codacy found an issue: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            System.exit(-1);
Codacy found an issue: [System.exit() should not be used in J2EE/JEE apps](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Codacy found an issue: [Avoid throwing null pointer exceptions.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    public static String replaceAnsiWithoutReset(String string) {
Codacy found an issue: [Avoid reassigning parameters such as 'string'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandCreate.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 459, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public List<Candidate> onTab(final long argsLength, final String lastWord, final ParsedLine parsedLine, final String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                                    if (argument.value().toLowerCase().startsWith(testString.toLowerCase())) {
Codacy found an issue: [These nested if statements could be combined](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public void onExecuteCommand(final CommandSender sender, final ParsedLine parsedLine, final String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandScreen.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 377, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +    public boolean bootstrap() {
Codacy found an issue: [The method 'bootstrap()' has an NPath complexity of 960, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    public static String replaceAnsi(String string) {
Codacy found an issue: [Avoid reassigning parameters such as 'string'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandInfo.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +public class AnsiColorReplacer {
Codacy found an issue: [The utility class name 'AnsiColorReplacer' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandShutdown.java
> +    public void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args) {
Codacy found an issue: [The method 'onExecuteCommand(CommandSender, ParsedLine, String)' has an NPath complexity of 321, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-08-28 17:08 UTC, byRoadrunner commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Codacy found an issue: [Use explicit scoping instead of the default package private level](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=5772472)

2020-09-28 17:33 UTC, GiantTreeLP requested changes
There is a lot to unpack. A lot of duplicate and similar code. A lot of code that's unnecessary. Please fix this and additionally your style settings.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandExecutor.java
> +     * @param parsedLine the line with jline parser
```suggestion
     * @param parsedLine the line parsed with the JLine parser

```

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +    }
`a` and `b` are everything but meaningful names for variables.
Please change this and document certain, hard to read, sections with comments.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +                System.out.println("Command not found. Use the command \"help\" for further information!");
Use logging instead of `System.out`

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +                                               "CloudNet-Terminal")
Interesting style

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/pom.xml
> +        <kotlin.code.style>official</kotlin.code.style>
Are we using Kotlin here?

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java
> +            return Ansi.ansi().fg(Ansi.Color.YELLOW).a(logRecord.getLevel().getName()).reset().toString();
Maybe cache these strings

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +            compile(ChatColor.BLACK, Ansi.ansi().a(Ansi.Attribute.RESET).fg(Ansi.Color.BLACK).boldOff().toString()),
```suggestion
            compile(ChatColor.BLACK, Ansi.ansi().reset().fg(Ansi.Color.BLACK).boldOff().toString()),
```

This is shorter and does the same according to the documentation.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java
> +public enum ChatColor {
Well, this doesn't really work anymore, as Minecraft now supports RGB 24-bit color.
Also: DON'T STEAL CODE FROM OTHER PROJECTS!

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudNetLauncher.java
> +        System.out.println(Ansi.ansi().reset().toString());*/
This needs to be removed

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandExecutor.java
> +    void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args);
All arguments are given in the instance of `ParsedLine`, why are they needed twice?
No, 0-indexing in `args` is NOT an argument.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public void onExecuteCommand(final CommandSender sender, final ParsedLine parsedLine, final String[] args) {
Fix this

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public List<Candidate> onTab(final long argsLength, final String lastWord, final ParsedLine parsedLine, final String[] args) {
Again, fix this

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/command/CommandConsole.java
> +    public List<Candidate> onTab(final long argsLength, final String lastWord, final ParsedLine parsedLine, final String[] args) {
Your code style could also benefit from rewriting this class.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/NetworkManager.java
> +import eu.cloudnetservice.cloudnet.v2.master.network.packet.out.PacketOutUpdateServerInfo;
I believe your style settings are not correct.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/network/packet/in/PacketInAuthHandler.java
> +                                                                                           ))).syncUninterruptibly();
This should be done easier with a custom object.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java
> +    v1_16_2("1.16.2", "https://cdn.getbukkit.org/spigot/spigot-%s.jar");
You are missing version 1.16.3.

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +                "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11").get();
We do have a constant for this

2020-09-28 17:33 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/spigot/SpigotBuilder.java
> +    static void deleteBuildFolder(File buildFolder) throws IOException {
Fix this

2020-09-29 12:12 UTC, TheMeinerLP commented on cloudnet-app-lib/cloudnet-logging/pom.xml
> +        <kotlin.code.style>official</kotlin.code.style>
No was a old implementation

2020-09-29 12:13 UTC, TheMeinerLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/LoggingFormatter.java
> +            return Ansi.ansi().fg(Ansi.Color.YELLOW).a(logRecord.getLevel().getName()).reset().toString();
Yes i make this as a Constant

2020-09-29 12:14 UTC, TheMeinerLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/ChatColor.java
> +public enum ChatColor {
Is only using for the console
In the console is not able to use more as the MinecraftColors

2020-09-29 12:15 UTC, TheMeinerLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandExecutor.java
> +    void onExecuteCommand(CommandSender sender, ParsedLine parsedLine, String[] args);
No the `ParsedLine` have morge options from JLine3 it self

2020-09-29 12:16 UTC, TheMeinerLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/setup/GetBukkitVersion.java
> +    v1_16_2("1.16.2", "https://cdn.getbukkit.org/spigot/spigot-%s.jar");
Was pushed bevor 1.16.3

2020-09-29 15:15 UTC, GiantTreeLP commented
Really? Did you even my comment about `AnsiColorReplacer.java`? Did you even read your own code?

You are using `a(Ansi.Attribute.RESET)` for every color and it doesn't even come to your mind to just simplify *all* calls?

I'm referring to this commit: https://github.com/CloudNetService/CloudNet/pull/289/commits/b22c573bc7e910315e0fb53a04ebd527bda4b127  
Please amend it.

2021-01-16 21:00 UTC, GiantTreeLP commented
Closes #279

2021-03-02 07:36 UTC, TheMeinerLP commented
Ready to review. All common functions are tested!

2021-03-03 17:53 UTC, GiantTreeLP requested changes

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +            System.out.println(parse.words().size());
Is this debug output supposed to be still in here?

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-command/src/main/java/eu/cloudnetservice/cloudnet/v2/command/CommandManager.java
> +    public void dispatch(final String line, final LineReader lineReader) {
Marker for myself: i may need to look into this method and optimize it a bit.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +        //AnsiConsole.systemInstall();
Comments like this should not be put into productive code

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +                                           //.attributes(attributes)
See above comment

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-console/src/main/java/eu/cloudnetservice/cloudnet/v2/console/ConsoleManager.java
> +            throw new NullPointerException("Console input dispatcher is empty");
Do not throw NPE explicitly!
Use a more descriptive one like IllegalStateException.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/MessengerPackage.java
> +/*
What is this class?

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/MultiValue.java
> +/*
Marker for myself: Remove this class

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/map/NetorHashMap.java
> +/*
Marker for myself: Remove this

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/map/NetorMap.java
> +/*
Marker for myself: Remove this

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/map/NetorSet.java
> +/*
Marker for myself: Remove this

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/CloudNet.java
> +import eu.cloudnetservice.cloudnet.v2.master.command.CommandClear;
Why is you IDE not folding these imports?
It should be in the configuration/our code style settings.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +        return module;
I just noticed, that this method will return `null`, when the module is not present.
We are using an Optional here, so it should be an empty Optional in that case.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java
> +                                  key ->  Integer.parseInt(key) <= 2));
A queue size of 1 is perfectly acceptable

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java
> +                                  key ->  Integer.parseInt(key) > 1024))
Less than 1 GB is acceptable

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java
> +                                      key -> key.split("\\.").length == 4 && !key.equalsIgnoreCase("127.0.0.1")))
This prevents IPv6 addresses from being used

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java
> +                    configuration.set("general.percentOfCPUForANewProxy", 100D);
I don't like these raw configuration strings.
They only accrue technical debt.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +                                      key -> key.split("\\.").length == 4 && !key.equalsIgnoreCase("127.0.0.1")))
This prevents IPv6 addresses from being used.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/ChangePasswordSetup.java
> +                                 "§aThis user is already registerd!",
This message is plain wrong.
You are allowed to change the password of an existing user and the user being registered is actually a requirement for this setup to succeed at all.

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/ChangePasswordSetup.java
> +                                 username -> true));
```suggestion
                                 password -> true));
```

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/ChangePasswordSetup.java
> +                                 username -> true));
```suggestion
                                 password -> true));
```

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/CreateUserSetup.java
> +                                 username -> true));
```suggestion
                                 password -> true));
```

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/CreateUserSetup.java
> +                                 "§aThis user is already registerd!",
You don't actually check this

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/user/CreateUserSetup.java
> +                                 username -> true));
```suggestion
                                 password  -> true));
```

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +        });*/
Don't leave comments like this in code

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandVersion.java
>                                                                                                                                .getImplementationVersion() + " by Dytanic");
You changed this in the master but not here in the wrapper

2021-03-03 17:53 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/server/GameServer.java
> +        for (String command : serverProcessMeta.getServerProcessParameters()) {
Marker for myself: Fix this

2021-03-03 18:24 UTC, TheMeinerLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/MessengerPackage.java
> +/*
Idk

2021-03-03 18:26 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupCreateWrapper.java
> +                                      key -> key.split("\\.").length == 4 && !key.equalsIgnoreCase("127.0.0.1")))
Was before Dual-Stack

2021-03-03 19:04 UTC, TheMeinerLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/command/CommandVersion.java
>                                                                                                                                .getImplementationVersion() + " by Dytanic");
Its a easter egg

2021-03-06 19:40 UTC, GiantTreeLP commented
Also please fix the resource leak as Gson a´does actually not close readers and streams

2021-04-11 13:29 UTC, TheMeinerLP commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/module/CloudModuleManager.java
> +        return module;
All possible positions are checked if present the content

2021-04-11 20:20 UTC, GiantTreeLP reviewed
Please also take into consideration the comments made by Codacy

2021-04-11 20:20 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +    private static final Pattern BG_HEX_REPLACE = Pattern.compile("B#[a-fA-F\\d]{6}");
Use proper groups for both regular expressions here

2021-04-11 20:20 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +            input = input.replace(matcher.group(), Ansi.ansi().bgRgb(Integer.parseInt(matcher.group().substring(2), 16)).toString());
Use the groups from the previous comment here.

2021-04-11 20:20 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +            input = input.replace(matcher.group(), Ansi.ansi().fgRgb(Integer.parseInt(matcher.group().substring(2), 16)).toString());
Use the groups from the previous comment here

2021-04-11 20:20 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +            string = string.replace(matcher.group(), Ansi.ansi().bgRgb(Integer.parseInt(matcher.group().substring(2), 16)).toString());
Use the groups from the previous comment here

2021-04-11 20:20 UTC, GiantTreeLP commented on cloudnet-app-lib/cloudnet-logging/src/main/java/eu/cloudnetservice/cloudnet/v2/logging/color/AnsiColorReplacer.java
> +            string = string.replace(matcher.group(), Ansi.ansi().fgRgb(Integer.parseInt(matcher.group().substring(2), 16)).toString());
Use the groups from the previous comment here

2021-04-15 18:02 UTC, GiantTreeLP commented
I would say, after 10 months of development, this PR is ready to merge.

2021-04-19 19:23 UTC, merged