🚧:IPv6 support
CloudNetService/CloudNet-v2 pull request #303
Opened 2020-08-18 22:25 UTC by GiantTreeLP

This pull request includes:

- [x] breaking changes
- [ ] no breaking changes

### Changes made to the repository:

This pull request changes part of the setup of the wrapper, allowing users to configure IPv6 and Dual Stack addresses (`0.0.0.0`).
On top of that, the API was changed to properly support Internet Addresses instead of strings.

### Documentation of test results:

Preliminary testing has been done locally on a dual stack capable machine.
Full test results will be coming soon.

### Related issues/discussions:

This is a follow-up to #281.
Closes #275.

2020-08-18 22:27 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/CloudConfig.java
> +                throw new RuntimeException("Folder path " + path.toAbsolutePath() + " could not be created", e);
Codacy found an issue: [Avoid throwing raw exception types.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-08-18 22:27 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 1
           

Complexity increasing per file
==============================
- cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/server/BungeeCord.java  2
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -8
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/server/ProxyProcessMeta.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693&bid=19778089)

2020-08-19 15:49 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 2
           

Complexity increasing per file
==============================
- cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/server/BungeeCord.java  2
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -8
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/server/ProxyProcessMeta.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693&bid=19778089)

2020-08-19 15:49 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-08-19 15:49 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [The method 'main(String)' has an NPath complexity of 432, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-09-28 16:44 UTC, GiantTreeLP commented
Issues found by @deepcode-ci-bot will be fixed after merge.

2020-09-28 16:48 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 2
           

Complexity increasing per file
==============================
- cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  2
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/server/BungeeCord.java  2
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -8
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/server/ProxyProcessMeta.java  -1
         

Clones removed
==============
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  -1
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693&bid=19778089)

2020-09-28 16:48 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-09-28 16:48 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [The method 'main(String)' has an NPath complexity of 432, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-09-28 17:45 UTC, derklaro requested changes

2020-09-28 17:45 UTC, derklaro commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/network/NetworkConnection.java
> +    }    @Override
Formatting is broken here

2020-09-28 17:45 UTC, derklaro commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java
> +        return Objects.equals(serviceId, that.serviceId);
Maybe `return Objects.equals(properties, that.properties) && Objects.equals(serviceId, that.serviceId);`

2020-09-28 17:45 UTC, derklaro commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/setup/SetupWrapper.java
> +                                   ex.printStackTrace();
Weired formatting here too

2020-09-28 17:53 UTC, TheMeinerLP reviewed
Looks good for me

2020-09-28 17:53 UTC, TheMeinerLP commented on cloudnet-api/cloudnet-api-bridge/src/main/java/eu/cloudnetservice/cloudnet/v2/bridge/CloudProxy.java
> +            e.printStackTrace();
Can you using the loger of bungeecord

2020-09-28 17:53 UTC, TheMeinerLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/network/NetworkConnection.java
> +            e.printStackTrace();
Add some logger usage

2020-09-28 17:53 UTC, TheMeinerLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java
> +    public ProxyProcessData(final ProxyProcessData proxyProcessData, final ServiceId serviceId) {
final maybe remove ?

2020-09-28 17:53 UTC, TheMeinerLP commented on cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapper.java
> +                e.printStackTrace();
Also add here the logger

2020-09-28 18:31 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java
> +        return Objects.equals(serviceId, that.serviceId);
Looking at the lines of codes preceding those: no, because otherwise, this would be eight calls chained together.

2020-09-28 18:35 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/network/NetworkConnection.java
> +            e.printStackTrace();
I don't have access to the central logger of any instance (master, wrapper, bridge) due to this class residing in the common network library.

2020-09-28 18:36 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java
> +    public ProxyProcessData(final ProxyProcessData proxyProcessData, final ServiceId serviceId) {
No, using final where possible promotes immutability

2020-09-28 18:41 UTC, byRoadrunner commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 2
           

Complexity increasing per file
==============================
- cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/server/BungeeCord.java  2
- cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  2
         

Complexity decreasing per file
==============================
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -8
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/server/ProxyProcessMeta.java  -1
         

Clones removed
==============
+ cloudnet-wrapper/src/main/java/eu/cloudnetservice/cloudnet/v2/wrapper/CloudNetWrapperConfig.java  -1
+ cloudnet-lib/src/main/java/eu/cloudnetservice/cloudnet/v2/lib/process/ProxyProcessData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693&bid=19778089)

2020-09-28 18:41 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [Avoid really long methods.](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-09-28 18:41 UTC, byRoadrunner commented on cloudnet-master/src/main/java/eu/cloudnetservice/cloudnet/v2/master/bootstrap/CloudBootstrap.java
> +    public static synchronized void main(String[] args) throws IOException {
Codacy found an issue: [The method 'main(String)' has an NPath complexity of 432, current threshold is 200](https://app.codacy.com/gh/CloudNetService/CloudNet/pullRequest?prid=6035693)

2020-10-06 15:19 UTC, merged