Fixed "Unverified Login" Bug
CloudNetService/CloudNet-v2 pull request #59
Opened 2018-10-16 10:45 UTC by Sarsum

I, hopefully, fixed the "Unverified Login" Bug when there is an empty file and a file with the name "null"

2018-10-16 13:48 UTC, derklaro requested changes

2018-10-16 13:48 UTC, KlaroYT commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
> +        if (database.containsDoc("null")) {
The Document must not have the Name "null" to get an "Unverirfied Login" it can also be broken, than you have to delete it an create an new one

2018-10-16 14:23 UTC, Sarsum commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
> +        if (database.containsDoc("null")) {
I did not know these Issue, the only issues I know are the ones with the "null" file

2018-10-16 16:29 UTC, KlaroYT commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
> +        if (database.containsDoc("null")) {
Yes there is an Bug. Check if the cloudplayer you get is null

2018-10-25 14:14 UTC, KlaroYT commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
> +        if (database.containsDoc("null")) {
You fixed nothing. You have only checked if the database contains a file named null.

2018-10-25 14:21 UTC, Sarsum commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
> +        if (database.containsDoc("null")) {
I knew only the one problem, that the file with the playername is empty and there is another file which contains the data from the player file, and this is what I fixed!

2018-11-30 09:26 UTC, GiantTreeLP commented
Is this still relevant?
If not, please close this pull request.

2018-11-30 12:43 UTC, closed without merging