Added broadcastMessage methods to PlayerExecutor
CloudNetService/CloudNet-v2 pull request #63
Opened 2018-10-22 15:14 UTC by McRuben

2018-10-23 15:27 UTC, GiantTreeLP commented
Can you add a broadcast method that takes a `BaseComponent[]` as well?

2018-10-25 12:14 UTC, KlaroYT commented
In my opinion you can remove it out of the CorePlayerExecutor because there will never come an implementation.

2018-10-25 12:26 UTC, einrobin commented
Why should I remove that out of the CorePlayerExecutor? I would use that broadcastMessage methods for my systems.

2018-10-25 12:51 UTC, KlaroYT commented
The CorePlayerExecutor and the PlayerExecutor are unused classes.
It's not needed to add some more methods, some are empty, when all other methods don't work.

It's a null instance

2018-10-25 12:53 UTC, McRuben commented
The CorePlayerExecutor ist used, of course. And I think I will implement those methods that are not implemented in it yet.

2018-10-25 13:20 UTC, KlaroYT commented
Yes it is used, but all other methods are not in use.  It don't make any sence to impent only 4 methos.

2018-10-25 14:01 UTC, McRuben commented
But I've already said that I will implement those unimplemented methods soon.

2018-10-27 08:45 UTC, GiantTreeLP requested changes
Please remove files that don't belong to this PR, change the target to development and check the copyright on the blatantly copied files.

As this is a bigger PR, please include tests to check whether the serialization is done correctly.

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/api/event/player/UpdatePlayerEvent.java
>  @Getter
This file has nothing to do with the pull request

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/database/PlayerDatabase.java
>  import de.dytanic.cloudnet.lib.player.PlayerConnection;
This file has nothing to do with the pull request

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/network/NetworkManager.java
This file has nothing to do with the pull request

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/ChatColor.java
> +package net.md_5.bungee.api;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/ChatMessageType.java
> +package net.md_5.bungee.api;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/BaseComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/ClickEvent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/ComponentBuilder.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/HoverEvent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/KeybindComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/Keybinds.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/ScoreComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/SelectorComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/TextComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/api/chat/TranslatableComponent.java
> +package net.md_5.bungee.api.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/BaseComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/ComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/KeybindComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/ScoreComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/SelectorComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/TextComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/TranslatableComponentSerializer.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:45 UTC, GiantTreeLP commented on cloudnet-lib/src/main/java/net/md_5/bungee/chat/TranslationRegistry.java
> +package net.md_5.bungee.chat;
Please mark where this file has come from and when in a comment above the package

2018-10-27 08:50 UTC, GiantTreeLP commented
Closed, please file proper PRs and don't add unrelated code.

2018-10-27 08:50 UTC, closed without merging