Some small code optimizings
CloudNetService/CloudNet-v2 pull request #70
Opened 2018-10-24 11:44 UTC by KlaroYT

2018-10-24 11:51 UTC, KlaroYT commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
> +            System.exit(0);
Really xD

2018-10-27 08:34 UTC, GiantTreeLP requested changes

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/bootstrap/CloudBootstrap.java
> +        if (Float.parseFloat(System.getProperty("java.class.version")) < 52D)
```suggestion
        if (Float.parseFloat(System.getProperty("java.class.version")) < 52F) 
```

Either compare Float to Float or Double to Double

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/bootstrap/CloudBootstrap.java
> +            System.out.println("This application needs at least Java 8 or 10.0.1!");
```suggestion
            System.out.println("This application needs at least Java 8!"); 
```

This is enough, Java 10 is obsolete now.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-core/src/main/java/de/dytanic/cloudnetcore/bootstrap/CloudBootstrap.java
> +            } catch (Exception ex) {}
I know, this wasn't in the original source, but please log all exceptions.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/CloudNetWrapperConfig.java
>              if (!Files.exists(Paths.get(devServicePath)))
```suggestion
            if (!Files.exists(Paths.get(devServicePath))) {
                Files.createDirectories(Paths.get(devServicePath));
            }
```

Please keep braces after if-statements

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
> +        if (Float.parseFloat(System.getProperty("java.class.version")) < 52D)
```suggestion
        if (Float.parseFloat(System.getProperty("java.class.version")) < 52F) 
```

Please compare floats to floats

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
> +            System.out.println("This application needs at least Java 8 or 10.0.1!");
```suggestion
            System.out.println("This application needs at least Java 8!"); 
```

This is enough, Java 10 is obsolete.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
>          if (optionSet.has("systemTimer"))
Please keep the braces after if.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
>              System.out.println("CloudNet-Wrapper RezSyM Version " + CloudBootstrap.class.getPackage().getImplementationVersion() + "-" + CloudBootstrap.class.getPackage().getSpecificationVersion());
Please keep the braces after if.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
> +            System.exit(0);
Yes, and please keep braces after if.

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
>              while (true)
Analogous to the ifs: Keep braces

2018-10-27 08:34 UTC, GiantTreeLP commented on cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/bootstrap/CloudBootstrap.java
> +                } catch (Exception ex) {}
Please log all exceptions

2018-10-27 17:58 UTC, closed without merging