Code reformat, spelling fix
CloudNetService/CloudNet-v2 pull request #97
Opened 2018-12-15 15:10 UTC by KlaroYT

2018-12-15 15:26 UTC, GiantTreeLP commented
looks good to me

2019-01-06 17:01 UTC, KlaroYT commented
Wenn ich mal ganz ehrlich sein soll, finde ich, dass dies das Schlimmste ist am CloudNET Developement. 
Es passiert einfach gar nichts mehr. 22 Tage ist fast ein Monat, andere PR's sind sogar bereits länger offen. Bitte einfach anders machen :) Danke.

2019-01-06 17:06 UTC, GiantTreeLP commented
Naja, wenn Joschua eine Review von Tarek erwartet.
Ich weiß nicht, ob die Änderung der Sichtbarkeit Fehler verursacht, aber solange die Cloud erfolgreich kompiliert wird, reicht mir das.

Ich merge das gleich.

Mit freundlichen Grüßen
Marvin Krüger

________________________________
From: _Klaro | Pasqual K. <notifications@github.com>
Sent: Sunday, January 6, 2019 6:01:54 PM
To: CloudNetService/CloudNet
Cc: Marvin; Assign
Subject: Re: [CloudNetService/CloudNet] Code reformat, spelling fix (#97)


Wenn ich mal ganz ehrlich sein soll, finde ich, dass dies das Schlimmste ist am CloudNET Developement.
Es passiert einfach gar nichts mehr. 22 Tage ist fast ein Monat, andere PR's sind sogar bereits länger offen. Bitte einfach anders machen :) Danke.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://github.com/CloudNetService/CloudNet/pull/97#issuecomment-451757111>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AB9LlovwNtBH8ljo4S6rfc5lFTD0QhHTks5vAiwCgaJpZM4ZUxdr>.

2019-01-06 17:22 UTC, ghost commented
Gut du möchtest eine Review dazu haben. Ich habe mir das bereits am dem Tag angeschaut, als du diese Pull Request ins Leben gerufen hast. Deine Veränderungen von CloudPermissible, was ein Schreibfehler von mir war, der mir nie aufgefallen ist, ist das einzige, was ich in dieser Pull Request als Code Reformat interessant finde. Die Variabel Namen zu ändern bsp. halte ich jetzt persönlich für nicht notwendig.  

Ich wollte nochmal über diese Pull Request anschauen und habe sie vergessen tut mir leid.

Man kann schlecht an einem Programm arbeiten, wenn man nicht weiß, was man noch machen soll.
Für mich persönlich, bietet es nicht mehr viel und ich denke, dass der Funktionsumfang ausreichend ist.

Fehler korrekturen hingegen sollten wirklich noch gemacht werden. Ich schreibe jedoch auch parallel an der 3.0 wo ich genauso noch Zeit brauche.

Und ich will dich darauf hinweisen, dass das Weihnachts und Neujahrszeit war innerhalb deiner geliebten 22 Tage.

2019-01-06 17:27 UTC, GiantTreeLP commented
Ja ne, ich merge das nicht.
Warum benennst du die logisch benannten handling Methoden alle in "handle" um?
Das reduziert die Lesbarkeit.

2019-01-06 17:29 UTC, GiantTreeLP requested changes
Einige gute Dinge sind dabei, aber auch einige schlechte.
Überarbeite die Benennung der Methoden nochmal.

2019-01-06 18:05 UTC, KlaroYT commented
Ist ja nicht so als hätte CN-GitHub Öffnungszeiten und wäre "Über die Feiertage geschlossen". Dieser Satz hätte doch gereicht und das verstehe ich nicht. Sonst ist doch alles in Ordnung -> Einfach hinschreiben = Fertig. :) Ich wollte auch nur drauf hinweisen und dich nicht angreifen @Dytanic aber deine Antwort klingt so, als würde ich dich persönlich töten wollen. 
Schon so ein Satz wie "Und ich will dich darauf hinweisen, dass das Weihnachts und Neujahrszeit war innerhalb deiner geliebten 22 Tage." finde ich nicht in Ordnung. Ich sehe auf Discord wann du online bist und du warst oft genug online. Außerdem hätte man das schon vor 22 Tagen schreiben können, wie du selber darauf hinweist ("Ich habe mir das bereits am dem Tag angeschaut, als du diese Pull Request ins Leben gerufen hast."). Aber anscheinend passt es euch ja nicht, dass man helfen will, was auch an den schnellen Meinungsänderungen liegen kann ("looks good to me" wird plötzlich zu "Ja ne, ich merge das nicht.
Warum benennst du die logisch benannten handling Methoden alle in "handle" um?
Das reduziert die Lesbarkeit." - finde ich nicht sehr nett; Hätte man von Anfang an schreiben können.). 

Wenn man nicht helfen soll, bitte darauf hinweisen oder direkt den Kommentar schreiben und nicht irgendwann. 

Für mich ist das ganze nun erledigt und ich will jetzt auch keinen Streit hier auslösen, nur mal meine Luft auslassen 
Schönen Abend noch :)

2019-01-06 18:05 UTC, closed without merging

2019-01-06 18:07 UTC, GiantTreeLP commented
Ich habs am Anfang nur überflogen und das sah eigentlich auch okay aus.
Da dachte ich mir auch, dass die Typen ja reichen, aber durch einige Logs und so ist mir aufgefallen, dass sowas nervt, weil man im Support dann immer in den Code sehen muss.
Du kannst deine PR gerne updaten, dann merge ich die, wenn die qualitativ passt.

Aber wenn du nicht möchtest, ist das auch in Ordnung.

2019-01-06 18:08 UTC, KlaroYT commented
Nach dem Kommentar da oben ganz bestimmt nie wieder.

2019-01-06 18:41 UTC, Dytanic commented
@KlaroYT  was ich privat mit der Software Discord mache, und auf welchen Medien ich dies nutze, wo mein bestimmter Status steht, sagen nicht direkt aus, wie aktiv ich Discord nutze. Aber wenn du dir da so sicher bist, es als Argument zu sehen, dann wundere ich mich, warum Personen anschreiben wenn ich Offline bin?

2019-01-06 20:08 UTC, byRoadrunner commented
Klärt das bitte nicht in einer PullRequest :)
Dann würde ich erstmal sagen hier #closed

2019-01-06 21:21 UTC, KlaroYT commented
Mir persönlich soll es jetzt egal sein, Ich wollte nur darauf hinweisen und
keinen Streit auslösen. Trotzdem danke für die schnellen antworten :)

Am So., 6. Jan. 2019, 19:41 hat Tareko <notifications@github.com>
geschrieben:

> @KlaroYT <https://github.com/KlaroYT> was ich privat mit der Software
> Discord mache, und auf welchen Medien ich dies nutze, wo mein bestimmter
> Status steht, sagen nicht direkt aus, wie aktiv ich Discord nutze. Aber
> wenn du dir da so sicher bist, es als Argument zu sehen, dann wundere ich
> mich, warum Personen anschreiben wenn ich Offline bin?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CloudNetService/CloudNet/pull/97#issuecomment-451764125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AmmAq_0ClRAHmu6EbS31qesRTtVQiUo-ks5vAkNLgaJpZM4ZUxdr>
> .
>